"use client";

import { useEffect, useMemo, useState } from "react";
import { jsPDF } from "jspdf";

type Session = { id: string; status: string; startedAt: string };
type Offer = { id: string; title: string; salaryText: string; companyName: string; roleLabel: string; createdAt: string };

function msToClock(ms: number) {
  const s = Math.max(0, Math.floor(ms / 1000));
  const m = Math.floor(s / 60);
  const r = s % 60;
  return `${m}:${r.toString().padStart(2, "0")}`;
}

export default function TechInterviewPage() {
  const userId = "demo-user";
  const [session, setSession] = useState<Session | null>(null);
  const [question, setQuestion] = useState<string>("");
  const [answer, setAnswer] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [log, setLog] = useState<string[]>([]);

  const [pendingOffer, setPendingOffer] = useState(false);
  const [offerReadyAt, setOfferReadyAt] = useState<number | null>(null);
  const [offer, setOffer] = useState<Offer | null>(null);
  const [showCongrats, setShowCongrats] = useState(false);

  const remainingMs = useMemo(() => (offerReadyAt ? offerReadyAt - Date.now() : 0), [offerReadyAt]);
  const canDownload = Boolean(offer);

  useEffect(() => {
    if (!offerReadyAt) return;
    const t = setInterval(() => {
      // force rerender
      if (Date.now() >= offerReadyAt) {
        setShowCongrats(true);
        setPendingOffer(false);
      }
    }, 1000);
    return (
    <>
      <div className="bgPattern" />
      <div className="heroBlur" />) => clearInterval(t);
  }, [offerReadyAt]);

  async function start() {
    setLoading(true);
    try {
      const res = await fetch("/api/interviews/tech/start", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ userId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error ?? "Failed");
      setSession(data.session);
      setQuestion(data.nextQuestion);
      setLog((l) => [...l, "Tech interview started."]);
    } catch (e: any) {
      alert(e.message ?? "Error");
    } finally {
      setLoading(false);
    }
  }

  async function submitTurn() {
    if (!session) return;
    setLoading(true);
    try {
      const res = await fetch("/api/interviews/tech/turn", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ sessionId: session.id, answer }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error ?? "Failed");
      setLog((l) => [...l, `You: ${answer}`, `Tech Lead: ${data.nextQuestion}`]);
      setAnswer("");
      setQuestion(data.nextQuestion);
    } catch (e: any) {
      alert(e.message ?? "Error");
    } finally {
      setLoading(false);
    }
  }

  async function fetchLatestOffer() {
    const res = await fetch(`/api/offers/latest?userId=${encodeURIComponent(userId)}`);
    const data = await res.json();
    if (res.ok) setOffer(data.offer ?? null);
  }

  async function finish() {
    if (!session) return;
    setLoading(true);
    try {
      const res = await fetch("/api/interviews/tech/finish", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ sessionId: session.id }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error ?? "Failed");

      setLog((l) => [...l, `Result: ${data.pass ? "PASS ✅" : "FAIL ❌"} — ${data.summary}`]);
      setSession(null);
      setQuestion("");

      if (data.pass) {
        // "Offer processing" delay of 10 minutes (as requested).
        const readyAt = Date.now() + 10 * 60 * 1000;
        setOfferReadyAt(readyAt);
        setPendingOffer(true);

        // Offer is created immediately server-side; we can fetch now and show later.
        await fetchLatestOffer();
      }
    } catch (e: any) {
      alert(e.message ?? "Error");
    } finally {
      setLoading(false);
    }
  }

  function downloadPDF() {
    if (!offer) return;
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("Mock Job Offer", 20, 22);

    doc.setFontSize(12);
    doc.text(`Company: ${offer.companyName}`, 20, 36);
    doc.text(`Role: ${offer.roleLabel}`, 20, 44);
    doc.text(`Title: ${offer.title}`, 20, 52);
    doc.text(`Compensation: ${offer.salaryText}`, 20, 60);
    doc.text(`Issued: ${new Date(offer.createdAt).toLocaleString()}`, 20, 68);

    doc.setFontSize(10);
    doc.text("This is a simulated offer generated by LevelUp Pro for practice and motivation.", 20, 86);
    doc.text("It is not an employment contract and does not guarantee a real job.", 20, 94);

    doc.save("LevelUpTech-Mock-Offer.pdf");
  }

  return (
    <main className="row">
      <div className="card" style={{ flex: "1 1 660px" }}>
        <h2 style={{ marginTop: 0 }}>Tech Interview (Final Step)</h2>
        <p><small>Pass this interview to earn your mock offer + 90-day badge.</small></p>

        {!session ? (
          <button className="gold" onClick={start} disabled={loading}>
            {loading ? "Starting..." : "Begin Tech Interview (Final Step)"}
          </button>
        ) : (
          <>
            <div className="card" style={{ marginTop: 12 }}>
              <p style={{ margin: 0 }}><b>Tech Lead:</b></p>
              <p style={{ margin: "6px 0 0 0" }}>{question}</p>
            </div>

            <label style={{ display: "block", marginTop: 12 }}>Your answer</label>
            <textarea rows={7} value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="Explain your troubleshooting steps, tools, and what you'd check first." />

            <div style={{ display: "flex", gap: 10, marginTop: 10, flexWrap: "wrap" }}>
              <button onClick={submitTurn} disabled={loading || answer.trim().length < 20}>
                {loading ? "Submitting..." : "Submit Answer"}
              </button>
              <button className="gold" onClick={finish} disabled={loading}>Finish + Score</button>
              <a href="/dashboard"><button>Back to Dashboard</button></a>
            </div>
          </>
        )}

        {pendingOffer && offerReadyAt && (
          <div className="card" style={{ marginTop: 14 }}>
            <p style={{ margin: 0 }}><b>Congrats — offer is being prepared…</b></p>
            <p style={{ margin: "6px 0 0 0" }}>
              <small>Your results were successful. A congratulations module will appear in {msToClock(offerReadyAt - Date.now())}.</small>
            </p>
          </div>
        )}
      </div>

      <div className="card" style={{ flex: "1 1 360px" }}>
        <h3 style={{ marginTop: 0 }}>Session log</h3>
        {log.length ? log.map((x, i) => <p key={i} style={{ margin: "6px 0" }}><small>{x}</small></p>) : <p><small>No session yet.</small></p>}
      </div>

      {showCongrats && (
        <div className="modalOverlay" onMouseDown={() => setShowCongrats(false)}>
          <div className="modal" onMouseDown={(e) => e.stopPropagation()}>
            <div className="modalHeader">
              <div>
                <b>Congratulations 🎉</b>
                <div><small>You passed the Tech Interview.</small></div>
              </div>
              <button className="danger" onClick={() => setShowCongrats(false)}>Close</button>
            </div>

            <div className="modalBody">
              {offer ? (
                <>
                  <div className="card">
                    <p style={{ margin: 0 }}><b>{offer.title}</b></p>
                    <p style={{ margin: "6px 0" }}><small>{offer.companyName} • {offer.roleLabel}</small></p>
                    <p style={{ margin: 0 }}><b>Compensation</b>: {offer.salaryText}</p>
                    <p style={{ margin: "6px 0 0 0" }}><small>Issued: {new Date(offer.createdAt).toLocaleString()}</small></p>
                  </div>

                  <div style={{ display: "flex", gap: 10, marginTop: 12, flexWrap: "wrap" }}>
                    <button className="gold" disabled={!canDownload} onClick={downloadPDF}>
                      Download Offer PDF
                    </button>
                    <a href="/dashboard"><button>View Dashboard</button></a>
                  </div>

                  <p style={{ marginTop: 12 }}><small>Note: This is a simulated offer for practice and motivation.</small></p>
                </>
              ) : (
                <p><small>Loading offer…</small></p>
              )}
            </div>
          </div>
        </div>
      )}
    </main>
    </>
  );
}
